"""Render the board UI's pieces from Colin M.L. Burnett's "cburnett" SVG set
(tools/pieces/cburnett, BSD licence - see LICENSE.txt there; the same set as
CST-GUI and Lichess).

  python tools/make_pieces_burnett.py [square_px] [board_dir]   (needs PySide6)

Writes src/<board_dir>/pieces.h in the same format as tools/make_pieces.py
(the DejaVu glyph set): for each colour and type (PAWN..KING) a square_px x
square_px image of (grey, alpha) byte pairs, blended at run time over the
square colour. The set is black and white only, so grey + alpha loses
nothing. Also writes dl/pieces_preview.png.
"""
import sys
from pathlib import Path

from PySide6.QtCore import QByteArray, QRectF, Qt
from PySide6.QtGui import QColor, QGuiApplication, QImage, QPainter
from PySide6.QtSvg import QSvgRenderer

SQ = int(sys.argv[1]) if len(sys.argv) > 1 else 60
BOARD_DIR = sys.argv[2] if len(sys.argv) > 2 else "ws7"
SS = 4  # supersampling, then a smooth downscale
ROOT = Path(__file__).resolve().parents[1]
SET = ROOT / "tools" / "pieces" / "cburnett"
TYPES = "PNBRQK"  # PAWN..KING, the engine's order

app = QGuiApplication(sys.argv[:1])


def render(path):
    r = QSvgRenderer(QByteArray(path.read_bytes()))
    big = QImage(SQ * SS, SQ * SS, QImage.Format_ARGB32)
    big.fill(0)
    p = QPainter(big)
    p.setRenderHint(QPainter.Antialiasing)
    r.render(p, QRectF(0, 0, SQ * SS, SQ * SS))
    p.end()
    return big.scaled(SQ, SQ, Qt.IgnoreAspectRatio, Qt.SmoothTransformation)


def grey_alpha(img):
    out = []
    for y in range(SQ):
        for x in range(SQ):
            c = QColor.fromRgba(img.pixel(x, y))
            a = c.alpha()
            g = round(0.299 * c.red() + 0.587 * c.green() + 0.114 * c.blue()) if a else 0
            out += [g, a]
    return out


pieces = {}
for c, side in enumerate("wb"):
    for t, ch in enumerate(TYPES):
        img = render(SET / f"{side}{ch}.svg")
        pieces[(c, t)] = (img, grey_alpha(img))

lines = [
    "// Generated by tools/make_pieces_burnett.py from the cburnett SVG set",
    "// (Colin M.L. Burnett, BSD licence, tools/pieces/cburnett) - do not edit.",
    "#pragma once",
    "#include <stdint.h>",
    f"#define PIECE_PX {SQ}",
    "// [colour][type][y][x][grey, alpha]",
    f"static const uint8_t PIECE_IMG[2][6][{SQ * SQ * 2}] = {{",
]
for c in range(2):
    lines.append("  {")
    for t in range(6):
        data = pieces[(c, t)][1]
        rows = [", ".join(str(v) for v in data[i : i + 24]) for i in range(0, len(data), 24)]
        lines.append("    {" + ",\n     ".join(rows) + "},")
    lines.append("  },")
lines.append("};")
(ROOT / "src" / BOARD_DIR / "pieces.h").write_text("\n".join(lines) + "\n")

# preview: both colours on light and dark squares
light, dark = QColor(240, 217, 181), QColor(181, 136, 99)
prev = QImage(SQ * 6, SQ * 4, QImage.Format_RGB32)
p = QPainter(prev)
for row in range(4):
    for t in range(6):
        p.fillRect(t * SQ, row * SQ, SQ, SQ, light if (row + t) % 2 == 0 else dark)
        p.drawImage(t * SQ, row * SQ, pieces[(row // 2, t)][0])
p.end()
(ROOT / "dl").mkdir(exist_ok=True)
prev.save(str(ROOT / "dl" / "pieces_preview.png"))
print(f"pieces.h written ({SQ}px, src/{BOARD_DIR}), preview dl/pieces_preview.png")
