"""Render the chess pieces for the board UI from DejaVu Sans' chess glyphs
(U+2654..U+265F; DejaVu fonts are under the permissive Bitstream Vera licence).

  python tools/make_pieces.py [square_px] [board_dir]    (needs Pillow)

Writes src/<board_dir>/pieces.h (default cores3; ws7 uses 60 px): for each colour and type (PAWN..KING), a
square_px x square_px image of (grey, alpha) byte pairs, blended at run time
over the square colour. White pieces: white body, black outline. Black pieces:
the solid black glyph (its detail lines show white) over a white body.
Also writes dl/pieces_preview.png.
"""
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont, ImageOps

SQ = int(sys.argv[1]) if len(sys.argv) > 1 else 30
BOARD_DIR = sys.argv[2] if len(sys.argv) > 2 else "cores3"
SS = 8  # supersampling
CLOSE = 4 * SS + 1  # gap closing for the body fill (odd, in supersampled px)
TTF = r"C:\Windows\Fonts\DejaVuSans.ttf"
ROOT = Path(__file__).resolve().parents[1]
WHITE_GLYPHS = "\u2659\u2658\u2657\u2656\u2655\u2654"  # PAWN..KING outlines
BLACK_GLYPHS = "\u265f\u265e\u265d\u265c\u265b\u265a"  # PAWN..KING solid

big = SQ * SS
font = ImageFont.truetype(TTF, int(big * 0.92))


def glyph(ch):
    """Glyph alpha at big size, centred on the square (by the white glyph's box)."""
    img = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(img)
    x0, y0, x1, y1 = d.textbbox((0, 0), ch, font=font)
    d.text(((big - (x1 - x0)) / 2 - x0, (big - (y1 - y0)) / 2 - y0), ch, font=font, fill=255)
    return img


def inside(outline, close=CLOSE):
    """Everything not reachable from the border without crossing the outline.
    The outline is dilated first so small gaps (the queen's crown) don't leak,
    and the filled shape is eroded back by the same amount."""
    b = outline.point(lambda v: 255 if v > 96 else 0).filter(ImageFilter.MaxFilter(close))
    flood = b.copy()
    ImageDraw.floodfill(flood, (0, 0), 128)
    filled = flood.point(lambda v: 0 if v == 128 else 255)
    return filled.filter(ImageFilter.MinFilter(close))


def down(img):
    return img.resize((SQ, SQ), Image.LANCZOS)


pieces = {}  # (colour, type) -> (grey, alpha) images at SQ
for t in range(6):
    wg, bg = glyph(WHITE_GLYPHS[t]), glyph(BLACK_GLYPHS[t])
    body = inside(wg)
    alpha = ImageChops.lighter(body, wg)
    # white piece: white body, black outline strokes
    grey_w = ImageOps.invert(wg)
    # black piece: black solid glyph over the white body
    grey_b = ImageOps.invert(ImageChops.lighter(bg, wg))
    a = down(alpha)
    pieces[(0, t)] = (down(grey_w), a)
    pieces[(1, t)] = (down(grey_b.point(lambda v: min(v, 235))), a)

# C header
lines = [
    "// Generated by tools/make_pieces.py from DejaVu Sans chess glyphs - do not edit.",
    "#pragma once",
    "#include <stdint.h>",
    f"#define PIECE_PX {SQ}",
    "// [colour][type][y][x][grey, alpha]",
    f"static const uint8_t PIECE_IMG[2][6][{SQ * SQ * 2}] = {{",
]
for c in range(2):
    lines.append("  {")
    for t in range(6):
        g, a = pieces[(c, t)]
        data = []
        for gv, av in zip(g.tobytes(), a.tobytes()):
            data += [gv, av]
        rows = [", ".join(str(v) for v in data[i : i + 24]) for i in range(0, len(data), 24)]
        lines.append("    {" + ",\n     ".join(rows) + "},")
    lines.append("  },")
lines.append("};")
(ROOT / "src" / BOARD_DIR / "pieces.h").write_text("\n".join(lines) + "\n")

# preview: both colours on light and dark squares, 4x
light, dark = (240, 217, 181), (181, 136, 99)
prev = Image.new("RGB", (SQ * 6, SQ * 4))
for row in range(4):
    for t in range(6):
        c = row // 2
        bgc = light if (row + t) % 2 == 0 else dark
        sqimg = Image.new("RGB", (SQ, SQ), bgc)
        g, a = pieces[(c, t)]
        sqimg.paste(Image.merge("RGB", (g, g, g)), (0, 0), a)
        prev.paste(sqimg, (t * SQ, row * SQ))
(ROOT / "dl").mkdir(exist_ok=True)
prev.resize((SQ * 6 * 4, SQ * 4 * 4), Image.NEAREST).save(ROOT / "dl" / "pieces_preview.png")
print(f"pieces.h written ({SQ}px), preview dl/pieces_preview.png")
